name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        
    - name: Install Cocoapods
      run: |
        gem install cocoapods
        pod install
      
    - name: Build iOS App
      run: |
        xcodebuild -workspace YourApp.xcworkspace -scheme YourScheme -configuration Release -archivePath $RUNNER_TEMP/YourApp.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      
    - name: Create IPA
      run: |
        mkdir -p Payload
        cp -r $RUNNER_TEMP/YourApp.xcarchive/Products/Applications/YourApp.app Payload/
        zip -r YourApp.ipa Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: app-ipa
        path: YourApp.ipa
